name: Deploy to S3 via OIDC

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

    
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: s3-deploy-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Show assumed AWS identity
        run: aws sts get-caller-identity

      - name: Install dependencies
        working-directory: ./aws-iac-07-dynamoDB/solution/bakehouse-app
        run: ./install.sh

      - name: CDK deploy
        working-directory: ./aws-iac-07-dynamoDB/solution/bakehouse-app
        run: npx cdk deploy --require-approval never

      - name: Print deployed URL
        run: |
          echo "✅ Deployment complete!"
